import type { AdmissionCriterion, CoreCourse, Program, ProgramRequirement } from "./types";

const FETCHED_AT = "2026-07-19T00:00:00.000Z";

type ProgramSeedPatch = Pick<Program,
  "id" | "institutionIds" | "name" | "categories" | "sourceUrl" | "faculty" | "degreeType" | "language" | "duration" | "ects" | "mode" |
  "intakes" | "deadline" | "tuition" | "tuitionEur" | "tuitionAcademicYear" | "applicationPlatform" | "premaster" | "quota" | "campusName" |
  "city" | "campusArea" | "locationNotes" | "coreCourses" | "admissionCriteria" | "requirements" | "overview" | "applicationDates" | "testRequirements" |
  "premasterInfo" | "applicationLinks"
>;

function course(name: string, nameZh: string, sourceUrl: string, tags: string[] = []): CoreCourse {
  return { name, nameZh, tags, creditsEcts: null, sourceUrl, originalText: name, summaryZh: nameZh };
}

function criterion(id: string, kind: AdmissionCriterion["kind"], title: string, description: string, sourceUrl: string, options: Partial<AdmissionCriterion> = {}): AdmissionCriterion {
  return { id, kind, title, description, sourceUrl, required: true, tags: [], verificationState: "confirmed", creditsEcts: null, summaryZh: description, ...options };
}

function requirement(id: string, materialType: ProgramRequirement["materialType"], title: string, originalText: string, sourceUrl: string): ProgramRequirement {
  return { id, category: "申请材料", materialType, required: true, title, titleOriginal: title, originalText, structuredRequirement: originalText, summaryZh: originalText, intake: "2026/27", sourceUrl, fetchedAt: FETCHED_AT, verificationState: "confirmed", confidence: 1 };
}

function define(input: Omit<ProgramSeedPatch, "degreeType" | "language" | "mode" | "applicationPlatform" | "premaster" | "quota" | "campusArea" | "applicationDates" | "testRequirements" | "premasterInfo"> & Partial<Pick<ProgramSeedPatch, "degreeType" | "language" | "mode" | "applicationPlatform" | "premaster" | "quota" | "campusArea" | "applicationDates" | "testRequirements" | "premasterInfo">>): ProgramSeedPatch {
  return {
    degreeType: "Master of Science (MSc)", language: "English", mode: "Full-time", applicationPlatform: "Studielink + university portal",
    premaster: "", quota: "", campusArea: "", applicationDates: [], testRequirements: [], premasterInfo: null,
    ...input,
  };
}

const STUDIELINK = "https://www.studielink.nl/";

export const catalogExpansionPrograms: ProgramSeedPatch[] = [
  define({
    id: "uva-bitm", institutionIds: ["uva"], name: "Business Information Technology Management", categories: ["business", "information", "computer"],
    sourceUrl: "https://abs.uva.nl/content/masters/business-information-technology-management/business-information-technology-management.html",
    faculty: "Amsterdam Business School", duration: "1 year", ects: "60 ECTS", intakes: ["September"], deadline: "", tuition: "待官网费用计算器确认", tuitionEur: null, tuitionAcademicYear: "2026/27",
    campusName: "Roeterseiland Campus", city: "Amsterdam", locationNotes: "商业战略、信息系统与颠覆性技术交叉项目。",
    overview: { title: "Business Information Technology Management", sourceUrl: "https://abs.uva.nl/content/masters/business-information-technology-management/business-information-technology-management.html", sourceTitle: "UvA programme page", originalText: "Understand disruptive technologies and their impact on business strategies.", summaryZh: "研究 AI、区块链、大数据等技术对商业战略、组织和信息系统的影响。", fetchedAt: FETCHED_AT, origin: "official", locked: false },
    coreCourses: [course("Theories of Business Information Technology Management", "商业信息技术管理理论", "https://abs.uva.nl/content/masters/business-information-technology-management/study-programme/study-programme.html", ["business", "information systems"]), course("Data Science and AI for Business", "商业数据科学与 AI", "https://abs.uva.nl/content/masters/business-information-technology-management/study-programme/study-programme.html", ["AI", "data"]), course("Cyber Security and IT/AI Auditing", "网络安全与 IT/AI 审计", "https://abs.uva.nl/content/masters/business-information-technology-management/study-programme/study-programme.html", ["information systems", "audit"])],
    admissionCriteria: [], requirements: [],
    applicationLinks: { programUrl: "https://abs.uva.nl/content/masters/business-information-technology-management/business-information-technology-management.html", curriculumUrl: "https://abs.uva.nl/content/masters/business-information-technology-management/study-programme/study-programme.html", eligibilityUrl: "https://abs.uva.nl/content/masters/business-information-technology-management/application-and-admission/application-and-admission.html", materialsUrl: "https://abs.uva.nl/content/masters/business-information-technology-management/application-and-admission/application-and-admission.html", careersUrl: "https://abs.uva.nl/content/masters/business-information-technology-management/careers/careers.html", premasterUrl: "", tuitionUrl: "https://abs.uva.nl/content/masters/business-information-technology-management/tuition-fee/tuition-fee.html", studielinkUrl: STUDIELINK },
  }),
  define({
    id: "uva-dsba-business-analytics", institutionIds: ["uva"], name: "Data Science and Business Analytics — Business Analytics", categories: ["business", "data", "computer"],
    sourceUrl: "https://www.uva.nl/en/programmes/masters/data-science-and-business-analytics/data-science-and-business-analytics.html",
    faculty: "Amsterdam School of Economics", duration: "1 year", ects: "60 ECTS", intakes: ["September"], deadline: "", tuition: "待官网费用计算器确认", tuitionEur: null, tuitionAcademicYear: "2026/27",
    campusName: "Roeterseiland Campus", city: "Amsterdam", locationNotes: "经济与商业学院项目；与 Information Studies — Data Science 为不同项目。",
    overview: { title: "Data Science and Business Analytics", sourceUrl: "https://www.uva.nl/en/programmes/masters/data-science-and-business-analytics/data-science-and-business-analytics.html", sourceTitle: "UvA programme page", originalText: "Solve business-related problems using computational approaches, advanced analytics and data science.", summaryZh: "用计算方法、高级分析和数据科学解决商业问题；本记录为 Business Analytics track。", fetchedAt: FETCHED_AT, origin: "official", locked: false },
    coreCourses: [course("Advanced Analytics for a Better World", "高级分析与决策", "https://www.uva.nl/en/programmes/masters/data-science-and-business-analytics-business-analytics/study-programme/study-programme.html", ["optimization", "machine learning"]), course("Supply Chain Analytics", "供应链分析", "https://www.uva.nl/en/programmes/masters/data-science-and-business-analytics-business-analytics/study-programme/study-programme.html", ["business", "analytics"])],
    admissionCriteria: [], requirements: [],
    applicationLinks: { programUrl: "https://www.uva.nl/en/programmes/masters/data-science-and-business-analytics/data-science-and-business-analytics.html", curriculumUrl: "https://www.uva.nl/en/programmes/masters/data-science-and-business-analytics-business-analytics/study-programme/study-programme.html", eligibilityUrl: "", materialsUrl: "", careersUrl: "", premasterUrl: "", tuitionUrl: "https://www.uva.nl/en/education/fees-and-funding/tuition-fees/tuition-fees.html", studielinkUrl: STUDIELINK },
  }),
  define({
    id: "vu-business-analytics", institutionIds: ["vu"], name: "Business Analytics", categories: ["business", "data", "computer"],
    sourceUrl: "https://vu.nl/en/education/master/business-analytics", faculty: "School of Business and Economics / Faculty of Science", duration: "2 years", ects: "120 ECTS", intakes: ["September"], deadline: "", tuition: "待官网费用表确认", tuitionEur: null, tuitionAcademicYear: "2026/27",
    campusName: "VU Campus", city: "Amsterdam", locationNotes: "两年制数理商业分析项目，覆盖从数据到决策支持系统的完整流程。",
    overview: { title: "Business Analytics", sourceUrl: "https://vu.nl/en/education/master/business-analytics", sourceTitle: "VU programme page", originalText: "Use data and algorithms to achieve business success.", summaryZh: "结合数学、计算机科学与经济学，通过统计、机器学习和优化把数据转化为决策。", fetchedAt: FETCHED_AT, origin: "official", locked: false },
    coreCourses: [course("Optimisation of Business Processes", "商业流程优化", "https://vu.nl/en/education/master/business-analytics", ["optimization"]), course("Computational Intelligence", "计算智能", "https://vu.nl/en/education/master/business-analytics", ["machine learning"]), course("Financial Risk Management", "金融风险管理", "https://vu.nl/en/education/master/business-analytics", ["finance", "statistics"])],
    admissionCriteria: [criterion("vu-ba-quant", "prerequisite", "定量课程背景", "本科应包含数学、计量经济学或计算机科学等充足定量课程；官网列示约 90 ECTS 的相关课程结构。", "https://vu.nl/en/education/master/business-analytics/admissions", { creditsEcts: 90, tags: ["mathematics", "econometrics", "computer science"] })],
    requirements: [requirement("vu-ba-transcript", "transcript", "成绩单", "提交相关本科学位的正式成绩单。", "https://vu.nl/en/education/master/business-analytics/admissions"), requirement("vu-ba-course-descriptions", "course_description", "课程描述", "用课程说明证明数学、计量与计算背景。", "https://vu.nl/en/education/master/business-analytics/admissions")],
    applicationLinks: { programUrl: "https://vu.nl/en/education/master/business-analytics", curriculumUrl: "https://vu.nl/en/education/master/business-analytics/curriculum", eligibilityUrl: "https://vu.nl/en/education/master/business-analytics/admissions", materialsUrl: "https://vu.nl/en/education/master/business-analytics/admissions", careersUrl: "https://vu.nl/en/education/master/business-analytics/future", premasterUrl: "", studielinkUrl: STUDIELINK },
  }),
  define({
    id: "rsm-bim", institutionIds: ["eur"], name: "Business Information Management", categories: ["business", "information", "data"],
    sourceUrl: "https://www.rsm.nl/education/master/msc-programmes/msc-business-information-management/", faculty: "Rotterdam School of Management", duration: "1 year", ects: "60 ECTS", intakes: ["September"], deadline: "15 May or earlier when full", tuition: "€25,800（非欧盟）", tuitionEur: 25800, tuitionAcademicYear: "2026/27", applicationPlatform: "Studielink + RSM OLAF",
    campusName: "Woudestein Campus", city: "Rotterdam", locationNotes: "项目有容量上限，达到申请上限时会早于 15 May 关闭。",
    overview: { title: "MSc Business Information Management", sourceUrl: "https://www.rsm.nl/education/master/msc-programmes/msc-business-information-management/", sourceTitle: "RSM programme page", originalText: "Explore digital technology and AI's impact on business.", summaryZh: "将信息管理作为战略资源，结合数字商业、数据科学和 IT 管理。", fetchedAt: FETCHED_AT, origin: "official", locked: false },
    coreCourses: [course("Information Strategy", "信息战略", "https://www.rsm.nl/education/master/msc-programmes/msc-business-information-management/", ["information systems", "business"]), course("Business Architecture and Transformation", "业务架构与转型", "https://www.rsm.nl/education/master/msc-programmes/msc-business-information-management/", ["digital transformation"]), course("Big Data Management and Applications", "大数据管理与应用", "https://www.rsm.nl/education/master/msc-programmes/msc-business-information-management/", ["data", "programming"])],
    admissionCriteria: [], requirements: [], quota: "Capped; closes at 500 applications or 15 May, whichever comes first",
    applicationLinks: { programUrl: "https://www.rsm.nl/education/master/msc-programmes/msc-business-information-management/", curriculumUrl: "https://www.rsm.nl/education/master/msc-programmes/msc-business-information-management/", eligibilityUrl: "https://www.rsm.nl/education/master/msc-programmes/msc-business-information-management/", materialsUrl: "https://www.rsm.nl/education/master/msc-programmes/how-to-apply/", careersUrl: "https://www.rsm.nl/education/master/msc-programmes/msc-business-information-management/", premasterUrl: "", studielinkUrl: STUDIELINK },
  }),
  define({
    id: "rsm-business-analytics-management", institutionIds: ["eur"], name: "Business Analytics & Management", categories: ["business", "data"],
    sourceUrl: "https://www.rsm.nl/education/master/msc-programmes/mscba-business-analytics-management/", faculty: "Rotterdam School of Management", duration: "1 year", ects: "60 ECTS", intakes: ["September"], deadline: "15 May or earlier when full", tuition: "€25,800（非欧盟）", tuitionEur: 25800, tuitionAcademicYear: "2026/27", applicationPlatform: "Studielink + RSM OLAF",
    campusName: "Woudestein Campus", city: "Rotterdam", locationNotes: "跨学科 MScBA 专门方向，项目可能在名额满时提前关闭。",
    overview: { title: "MScBA Business Analytics & Management", sourceUrl: "https://www.rsm.nl/education/master/msc-programmes/mscba-business-analytics-management/", sourceTitle: "RSM programme page", originalText: "Understand, solve and communicate challenges from data in organisations.", summaryZh: "围绕组织中的战略、战术和运营问题，训练商业分析项目管理与数据驱动决策。", fetchedAt: FETCHED_AT, origin: "official", locked: false },
    coreCourses: [course("Business Analytics Workshop", "商业分析工作坊", "https://www.rsm.nl/education/master/msc-programmes/mscba-business-analytics-management/", ["analytics", "business"]), course("Master Thesis", "硕士论文", "https://www.rsm.nl/education/master/msc-programmes/mscba-business-analytics-management/", ["research methods"])],
    admissionCriteria: [], requirements: [], quota: "Capped; may close before 15 May",
    applicationLinks: { programUrl: "https://www.rsm.nl/education/master/msc-programmes/mscba-business-analytics-management/", curriculumUrl: "https://www.rsm.nl/education/master/msc-programmes/mscba-business-analytics-management/", eligibilityUrl: "https://www.rsm.nl/education/master/msc-programmes/mscba-business-analytics-management/", materialsUrl: "https://www.rsm.nl/education/master/msc-programmes/how-to-apply/", careersUrl: "https://www.rsm.nl/education/master/msc-programmes/mscba-business-analytics-management/", premasterUrl: "", studielinkUrl: STUDIELINK },
  }),
  define({
    id: "leiden-cs-business-studies", institutionIds: ["leiden"], name: "Computer Science — Business Studies", categories: ["business", "information", "computer"],
    sourceUrl: "https://www.universiteitleiden.nl/en/education/study-programmes/master/computer-science/computer-science-and-business-studies", faculty: "Faculty of Science / LIACS", duration: "2 years", ects: "120 ECTS", intakes: ["September", "February"], deadline: "1 April（需签证，September intake）", tuition: "待官网费用表确认", tuitionEur: null, tuitionAcademicYear: "2026/27",
    campusName: "Leiden Science Campus", city: "Leiden", locationNotes: "现行后继项目；原 ICT in Business and the Public Sector 自 2025 年 9 月起停止招新。",
    overview: { title: "Computer Science and Business Studies", sourceUrl: "https://www.universiteitleiden.nl/en/education/study-programmes/master/computer-science/computer-science-and-business-studies/why-leiden-university", sourceTitle: "Leiden programme page", originalText: "Combine research in Computer Science with different aspects of business studies.", summaryZh: "把计算机科学研究与商业原则、管理训练和产业实践结合。", fetchedAt: FETCHED_AT, origin: "official", locked: false },
    coreCourses: [course("Business Studies", "商业研究模块", "https://www.universiteitleiden.nl/en/education/preview/study-programmes/master/computer-science/computer-science-and-business-studies/about-the-programme/programme-structure", ["business", "management"]), course("Computer Science Research Project", "计算机科学研究项目", "https://www.universiteitleiden.nl/en/education/preview/study-programmes/master/computer-science/computer-science-and-business-studies/about-the-programme/programme-structure", ["computer science", "research methods"])],
    admissionCriteria: [criterion("leiden-csbs-cs", "prerequisite", "计算机科学背景", "需达到荷兰计算机科学或人工智能学士同等水平，并累计至少 90 ECTS 的计算机科学课程与项目。", "https://www.universiteitleiden.nl/en/education/study-programmes/master/computer-science/computer-science-and-business-studies/admission-and-application/required-documents", { creditsEcts: 90, tags: ["computer science", "programming", "software engineering"] })],
    requirements: [requirement("leiden-csbs-transcript", "transcript", "学位与成绩单", "提交学位证与成绩单；未毕业者提交当前成绩及待修课程。", "https://www.universiteitleiden.nl/en/education/study-programmes/master/computer-science/computer-science-and-business-studies/admission-and-application/required-documents"), requirement("leiden-csbs-placement", "application_form", "Placement letter", "说明已达到计算机科学/人工智能学士同等水平及 90 ECTS 计算机课程。", "https://www.universiteitleiden.nl/en/education/study-programmes/master/computer-science/computer-science-and-business-studies/admission-and-application/required-documents")],
    applicationLinks: { programUrl: "https://www.universiteitleiden.nl/en/education/study-programmes/master/computer-science/computer-science-and-business-studies", curriculumUrl: "https://www.universiteitleiden.nl/en/education/preview/study-programmes/master/computer-science/computer-science-and-business-studies/about-the-programme/programme-structure", eligibilityUrl: "https://www.universiteitleiden.nl/en/education/study-programmes/master/computer-science/computer-science-and-business-studies/admission-and-application", materialsUrl: "https://www.universiteitleiden.nl/en/education/study-programmes/master/computer-science/computer-science-and-business-studies/admission-and-application/required-documents", careersUrl: "", premasterUrl: "", studielinkUrl: STUDIELINK },
  }),
  define({
    id: "leiden-statistics-data-science", institutionIds: ["leiden"], name: "Statistics & Data Science", categories: ["data"],
    sourceUrl: "https://www.universiteitleiden.nl/en/education/study-programmes/master/statistics--data-science", faculty: "Faculty of Science / LUMC / Faculty of Social and Behavioural Sciences", duration: "2 years", ects: "120 ECTS", intakes: ["September"], deadline: "", tuition: "待官网费用表确认", tuitionEur: null, tuitionAcademicYear: "2026/27",
    campusName: "Leiden University", city: "Leiden", locationNotes: "聚焦生命与行为科学应用；官网明确不以金融或商业分析为培养目标。",
    overview: { title: "Statistics & Data Science", sourceUrl: "https://www.universiteitleiden.nl/en/education/preview/study-programmes/master/statistics--data-science", sourceTitle: "Leiden programme page", originalText: "Statistical modelling and data analysis with applications in life and behavioural sciences.", summaryZh: "系统学习统计建模、数据分析和数据科学，重点应用于生命与行为科学。", fetchedAt: FETCHED_AT, origin: "official", locked: false },
    coreCourses: [course("Statistical Modelling", "统计建模", "https://www.universiteitleiden.nl/en/education/preview/study-programmes/master/statistics--data-science", ["statistics"]), course("Data Analysis", "数据分析", "https://www.universiteitleiden.nl/en/education/preview/study-programmes/master/statistics--data-science", ["data"]), course("Simulation and Optimisation", "仿真与优化", "https://www.universiteitleiden.nl/en/education/preview/study-programmes/master/statistics--data-science", ["optimization"])],
    admissionCriteria: [criterion("leiden-sds-quant", "prerequisite", "定量方法基础", "申请人需具备足够的数学、统计或应用领域定量方法基础。", "https://www.universiteitleiden.nl/en/education/preview/study-programmes/master/statistics--data-science", { tags: ["mathematics", "statistics"] })], requirements: [],
    applicationLinks: { programUrl: "https://www.universiteitleiden.nl/en/education/study-programmes/master/statistics--data-science", curriculumUrl: "https://www.universiteitleiden.nl/en/education/preview/study-programmes/master/statistics--data-science", eligibilityUrl: "https://www.universiteitleiden.nl/en/education/preview/study-programmes/master/statistics--data-science", materialsUrl: "", careersUrl: "", premasterUrl: "", studielinkUrl: STUDIELINK },
  }),
  define({
    id: "rug-information-science", institutionIds: ["rug"], name: "Information Science", categories: ["information", "computer", "data"],
    sourceUrl: "https://www.rug.nl/masters/information-science/?lang=en", faculty: "Faculty of Arts", duration: "1 year", ects: "60 ECTS", intakes: ["September"], deadline: "1 May 2027（非欧盟）", tuition: "€19,900（非欧盟）", tuitionEur: 19900, tuitionAcademicYear: "2026/27",
    campusName: "University of Groningen", city: "Groningen", locationNotes: "Communication & Information Studies 下的 Information Science track。",
    overview: { title: "Information Science", sourceUrl: "https://www.rug.nl/masters/information-science/?lang=en", sourceTitle: "RUG programme page", originalText: "Develop and assess smart applications using AI and language technology.", summaryZh: "以语言技术和 AI 为核心，分析非结构化数据并开发智能搜索、对话与语义应用。", fetchedAt: FETCHED_AT, origin: "official", locked: false },
    coreCourses: [course("Semantic Web Technology", "语义网技术", "https://www.rug.nl/masters/information-science/?lang=en", ["information systems"]), course("Language Models and Applications", "语言模型与应用", "https://www.rug.nl/masters/information-science/?lang=en", ["AI", "programming"]), course("Computational Semantics", "计算语义学", "https://www.rug.nl/masters/information-science/?lang=en", ["AI"])],
    admissionCriteria: [criterion("rug-is-background", "degree", "相关学位背景", "Information Science、AI、Data Science and Society 或课程高度重合的相关学位；不足时可能需要 pre-master。", "https://www.rug.nl/masters/information-science/?lang=en", { tags: ["information science", "artificial intelligence", "data science"] })], requirements: [], premaster: "可能提供 30–60 ECTS pre-master",
    applicationLinks: { programUrl: "https://www.rug.nl/masters/information-science/?lang=en", curriculumUrl: "https://www.rug.nl/masters/information-science/?lang=en", eligibilityUrl: "https://www.rug.nl/masters/information-science/?lang=en", materialsUrl: "", careersUrl: "https://www.rug.nl/masters/information-science/?lang=en", premasterUrl: "https://www.rug.nl/masters/information-science/?lang=en", studielinkUrl: STUDIELINK },
  }),
  define({
    id: "rug-marketing-analytics-data-science", institutionIds: ["rug"], name: "Marketing — Marketing Analytics and Data Science", categories: ["business", "data"],
    sourceUrl: "https://www.rug.nl/masters/msc-marketing-marketing-analytics-and-data-science/?lang=en", faculty: "Faculty of Economics and Business", duration: "1 year", ects: "60 ECTS", intakes: ["September"], deadline: "", tuition: "€22,200（非欧盟）", tuitionEur: 22200, tuitionAcademicYear: "2026/27",
    campusName: "University of Groningen", city: "Groningen", locationNotes: "MSc Marketing 下的 Marketing Analytics and Data Science profile。",
    overview: { title: "Marketing Analytics and Data Science", sourceUrl: "https://www.rug.nl/masters/msc-marketing-marketing-analytics-and-data-science/?lang=en", sourceTitle: "RUG programme page", originalText: "Use advanced statistical techniques to analyse data and design marketing strategy.", summaryZh: "用高级统计与数字分析工具提炼消费者洞察、评估并设计营销策略。", fetchedAt: FETCHED_AT, origin: "official", locked: false },
    coreCourses: [course("Marketing Analytics", "营销分析", "https://www.rug.nl/masters/msc-marketing-marketing-analytics-and-data-science/?lang=en", ["marketing", "statistics"]), course("Data Science", "数据科学", "https://www.rug.nl/masters/msc-marketing-marketing-analytics-and-data-science/?lang=en", ["data", "programming"])], admissionCriteria: [], requirements: [],
    applicationLinks: { programUrl: "https://www.rug.nl/masters/msc-marketing-marketing-analytics-and-data-science/?lang=en", curriculumUrl: "https://www.rug.nl/masters/msc-marketing-marketing-analytics-and-data-science/?lang=en", eligibilityUrl: "https://www.rug.nl/masters/msc-marketing-marketing-analytics-and-data-science/?lang=en", materialsUrl: "", careersUrl: "https://www.rug.nl/masters/msc-marketing-marketing-analytics-and-data-science/?lang=en", premasterUrl: "https://www.rug.nl/feb/education/study-programmes/pre-msc/customized-entry-packages/msc-marketing", studielinkUrl: STUDIELINK },
  }),
  define({
    id: "rug-technology-operations-management", institutionIds: ["rug"], name: "Technology and Operations Management", categories: ["business", "data", "computer"],
    sourceUrl: "https://www.rug.nl/masters/technology-and-operations-management/?lang=en", faculty: "Faculty of Economics and Business", duration: "1 year", ects: "60 ECTS", intakes: ["September", "February"], deadline: "1 May 2027（September，非欧盟）", tuition: "€22,200（非欧盟）", tuitionEur: 22200, tuitionAcademicYear: "2026/27",
    campusName: "University of Groningen", city: "Groningen", locationNotes: "可侧重 Digitalization and AI 或 Energy Transition and Climate Change。",
    overview: { title: "Technology and Operations Management", sourceUrl: "https://www.rug.nl/masters/technology-and-operations-management/?lang=en", sourceTitle: "RUG programme page", originalText: "Use big data, analytical tools, and strategies to develop resilient business solutions.", summaryZh: "以数据分析、数据科学、编程和仿真研究运营流程与管理决策。", fetchedAt: FETCHED_AT, origin: "official", locked: false },
    coreCourses: [course("Data Science", "数据科学", "https://www.rug.nl/masters/technology-and-operations-management/?lang=en", ["data"]), course("Programming", "编程", "https://www.rug.nl/masters/technology-and-operations-management/?lang=en", ["programming"]), course("Mathematical Modelling and Simulation", "数学建模与仿真", "https://www.rug.nl/masters/technology-and-operations-management/?lang=en", ["mathematics", "simulation"])], admissionCriteria: [], requirements: [],
    applicationLinks: { programUrl: "https://www.rug.nl/masters/technology-and-operations-management/?lang=en", curriculumUrl: "https://www.rug.nl/masters/technology-and-operations-management/?lang=en", eligibilityUrl: "https://www.rug.nl/masters/technology-and-operations-management/?lang=en", materialsUrl: "", careersUrl: "https://www.rug.nl/masters/technology-and-operations-management/?lang=en", premasterUrl: "https://www.rug.nl/feb/premaster", studielinkUrl: STUDIELINK },
  }),
  define({
    id: "uu-applied-data-science", institutionIds: ["uu"], name: "Applied Data Science", categories: ["data", "computer"],
    sourceUrl: "https://www.uu.nl/en/masters/applied-data-science", faculty: "Faculty of Science", duration: "1 year", ects: "60 ECTS", intakes: ["September"], deadline: "", tuition: "€25,306（非欧盟）", tuitionEur: 25306, tuitionAcademicYear: "2026/27",
    campusName: "Utrecht University", city: "Utrecht", locationNotes: "一年制高强度、跨领域应用型学术硕士；项目为 selective。",
    overview: { title: "Applied Data Science", sourceUrl: "https://www.uu.nl/en/masters/applied-data-science", sourceTitle: "UU programme page", originalText: "Apply data science techniques in five different focus domains.", summaryZh: "把数据科学技术与健康、经济、地学、社会行为和媒体等领域知识结合。", fetchedAt: FETCHED_AT, origin: "official", locked: false },
    coreCourses: [course("Responsible AI and Data Ethics", "负责任 AI 与数据伦理", "https://www.uu.nl/en/masters/applied-data-science/study-programme", ["AI", "ethics"]), course("Visual Analytics for Big Data", "大数据可视分析", "https://www.uu.nl/en/masters/applied-data-science/study-programme", ["data"]), course("Text and Media Analytics", "文本与媒体分析", "https://www.uu.nl/en/masters/applied-data-science/study-programme", ["data", "AI"])], admissionCriteria: [], requirements: [], quota: "Selective programme",
    applicationLinks: { programUrl: "https://www.uu.nl/en/masters/applied-data-science", curriculumUrl: "https://www.uu.nl/en/masters/applied-data-science/study-programme", eligibilityUrl: "https://www.uu.nl/en/masters/applied-data-science/application-and-admission", materialsUrl: "https://www.uu.nl/en/masters/applied-data-science/application-and-admission", careersUrl: "https://www.uu.nl/en/masters/applied-data-science/career-prospects", premasterUrl: "", tuitionUrl: "https://www.uu.nl/en/masters/applied-data-science/tuition-fees-and-financial-support", studielinkUrl: STUDIELINK },
  }),
  define({
    id: "maastricht-dsdm", institutionIds: ["maastricht"], name: "Data Science for Decision Making", categories: ["data", "computer"],
    sourceUrl: "https://www.maastrichtuniversity.nl/education/master/programmes/data-science-decision-making", faculty: "Faculty of Science and Engineering / Department of Advanced Computing Sciences", duration: "2 years", ects: "120 ECTS", intakes: ["September", "February"], deadline: "1 May（September，非欧盟）/ 1 November（February，非欧盟）", tuition: "待官网费用表确认", tuitionEur: null, tuitionAcademicYear: "2026/27",
    campusName: "Maastricht University", city: "Maastricht", locationNotes: "应用数学、运筹优化与计算机科学交叉项目。",
    overview: { title: "Data Science for Decision Making", sourceUrl: "https://www.maastrichtuniversity.nl/education/master/programmes/data-science-decision-making/why-this-programme", sourceTitle: "UM programme page", originalText: "Methods, techniques and algorithms for mathematical modelling and decision making.", summaryZh: "用应用数学、算法和数据科学分析并优化流程、运营和复杂决策。", fetchedAt: FETCHED_AT, origin: "official", locked: false },
    coreCourses: [course("Production Planning and Supply Chain Optimisation", "生产计划与供应链优化", "https://www.maastrichtuniversity.nl/education/master/programmes/data-science-decision-making/why-this-programme", ["optimization", "supply chain"]), course("Algorithms for Big Data", "大数据算法", "https://www.maastrichtuniversity.nl/education/master/programmes/data-science-decision-making/why-this-programme", ["programming", "data"]), course("Decision Making under Randomness", "随机环境决策", "https://www.maastrichtuniversity.nl/education/master/programmes/data-science-decision-making/why-this-programme", ["probability", "simulation"])],
    admissionCriteria: [criterion("um-dsdm-math", "prerequisite", "数学基础", "需具备微积分、线性代数、离散数学、概率与统计等扎实数学背景。", "https://www.maastrichtuniversity.nl/education/master/programmes/data-science-decision-making/admission-requirements", { tags: ["calculus", "linear algebra", "probability", "statistics"] }), criterion("um-dsdm-cs", "prerequisite", "计算机科学基础", "需掌握数据结构、算法和至少一种编程语言。", "https://www.maastrichtuniversity.nl/education/master/programmes/data-science-decision-making/admission-requirements", { tags: ["algorithms", "programming"] })],
    requirements: [requirement("um-dsdm-photo", "other", "近期证件照", "按 MyApplication 任务规格上传近期证件照。", "https://www.maastrichtuniversity.nl/education/master/programmes/data-science-decision-making/admission-requirements"), requirement("um-dsdm-passport", "passport", "护照 / 身份证件", "提交有效护照或欧盟身份证件。", "https://www.maastrichtuniversity.nl/education/master/programmes/data-science-decision-making/admission-requirements"), requirement("um-dsdm-transcript", "transcript", "成绩单", "提交最新成绩单。", "https://www.maastrichtuniversity.nl/education/master/programmes/data-science-decision-making/admission-requirements"), requirement("um-dsdm-diploma", "degree_certificate", "学位证书", "已毕业者提交学位证书。", "https://www.maastrichtuniversity.nl/education/master/programmes/data-science-decision-making/admission-requirements")],
    applicationLinks: { programUrl: "https://www.maastrichtuniversity.nl/education/master/programmes/data-science-decision-making", curriculumUrl: "https://www.maastrichtuniversity.nl/education/master/programmes/data-science-decision-making/courses-curriculum", eligibilityUrl: "https://www.maastrichtuniversity.nl/education/master/programmes/data-science-decision-making/admission-requirements", materialsUrl: "https://www.maastrichtuniversity.nl/education/master/programmes/data-science-decision-making/admission-requirements", careersUrl: "https://www.maastrichtuniversity.nl/education/master/programmes/data-science-decision-making/your-future", premasterUrl: "https://www.maastrichtuniversity.nl/nl/premaster-voor-de-msc-data-science-decision-making", studielinkUrl: STUDIELINK },
  }),
  define({
    id: "radboud-dsai", institutionIds: ["radboud"], name: "Computing Science — Data Science and AI", categories: ["data", "computer"],
    sourceUrl: "https://www.ru.nl/en/education/masters/data-science-and-ai", faculty: "Faculty of Science / iCIS", duration: "2 years", ects: "120 ECTS", intakes: ["September"], deadline: "", tuition: "€25,429（非欧盟）", tuitionEur: 25429, tuitionAcademicYear: "2026/27",
    campusName: "Heyendaal Campus", city: "Nijmegen", locationNotes: "Computing Science 下的研究型 Data Science and AI specialisation。",
    overview: { title: "Data Science and AI", sourceUrl: "https://www.ru.nl/en/education/masters/data-science-and-ai", sourceTitle: "Radboud programme page", originalText: "Transform data into knowledge and solutions using machine learning and AI.", summaryZh: "以机器学习、概率建模、信息检索和推荐系统为核心，把数据转化为知识与解决方案。", fetchedAt: FETCHED_AT, origin: "official", locked: false },
    coreCourses: [course("Machine Learning", "机器学习", "https://www.ru.nl/en/education/masters/data-science-and-ai", ["machine learning"]), course("Information Retrieval", "信息检索", "https://www.ru.nl/en/education/masters/data-science-and-ai", ["information systems"]), course("Probabilistic Modelling", "概率建模", "https://www.ru.nl/en/education/masters/data-science-and-ai", ["probability", "statistics"])],
    admissionCriteria: [criterion("ru-dsai-math", "prerequisite", "数学课程", "需至少 12 ECTS 的微积分、线性代数、逻辑、统计、图论或概率等数学课程。", "https://www.ru.nl/en/education/masters/data-science-and-ai/admission-and-application", { creditsEcts: 12, tags: ["mathematics"] }), criterion("ru-dsai-cs", "prerequisite", "理论计算机课程", "需至少 12 ECTS 的 AI、数据分析、机器学习、数据挖掘、信息建模或数据库等课程。", "https://www.ru.nl/en/education/masters/data-science-and-ai/admission-and-application", { creditsEcts: 12, tags: ["computer science", "AI"] }), criterion("ru-dsai-thesis", "prerequisite", "本科论文 / 项目", "需完成至少 10 ECTS 的本科毕业项目或论文。", "https://www.ru.nl/en/education/masters/data-science-and-ai/admission-and-application", { creditsEcts: 10, tags: ["research methods"] })], requirements: [],
    applicationLinks: { programUrl: "https://www.ru.nl/en/education/masters/data-science-and-ai", curriculumUrl: "https://www.ru.nl/en/education/masters/data-science-and-ai/study-programme", eligibilityUrl: "https://www.ru.nl/en/education/masters/data-science-and-ai/admission-and-application", materialsUrl: "https://www.ru.nl/en/education/masters/data-science-and-ai/admission-and-application", careersUrl: "https://www.ru.nl/en/education/masters/data-science-and-ai", premasterUrl: "", tuitionUrl: "https://www.ru.nl/en/education/masters/data-science-and-ai/tuition", studielinkUrl: STUDIELINK },
  }),
  define({
    id: "tilburg-baor", institutionIds: ["tilburg"], name: "Business Analytics and Operations Research", categories: ["business", "data"],
    sourceUrl: "https://www.tilburguniversity.edu/education/masters-programs/business-analytics-and-operations-research", faculty: "Tilburg School of Economics and Management", duration: "1 year", ects: "60 ECTS", intakes: ["End of August", "End of January"], deadline: "", tuition: "€23,900（非欧盟）", tuitionEur: 23900, tuitionAcademicYear: "2026/27",
    campusName: "Tilburg University Campus", city: "Tilburg", locationNotes: "可选择 Business Analytics 或 Operations Research track。",
    overview: { title: "Business Analytics and Operations Research", sourceUrl: "https://www.tilburguniversity.edu/education/masters-programs/business-analytics-and-operations-research", sourceTitle: "Tilburg programme page", originalText: "Analyze data to develop and apply analytical models to business.", summaryZh: "使用优化、机器学习和供应链分析建立模型，支持复杂商业决策。", fetchedAt: FETCHED_AT, origin: "official", locked: false },
    coreCourses: [course("Machine Learning Analytics", "机器学习分析", "https://www.tilburguniversity.edu/education/masters-programs/business-analytics-and-operations-research", ["machine learning"]), course("Supply Chain Analytics", "供应链分析", "https://www.tilburguniversity.edu/education/masters-programs/business-analytics-and-operations-research", ["supply chain"]), course("Decision Making under Uncertainty", "不确定性决策", "https://www.tilburguniversity.edu/education/masters-programs/business-analytics-and-operations-research", ["probability", "optimization"])],
    admissionCriteria: [criterion("tilburg-baor-degree", "degree", "计量经济学或相关定量学位", "最佳准备背景为 Econometrics and Operations Research 或招生委员会认可的相近定量专业。", "https://www.tilburguniversity.edu/education/masters-programs/business-analytics-and-operations-research", { tags: ["econometrics", "operations research"] })], requirements: [], premaster: "研究型大学申请人可能获得 6–30 ECTS 定制 pre-master；HBO 不适用",
    applicationLinks: { programUrl: "https://www.tilburguniversity.edu/education/masters-programs/business-analytics-and-operations-research", curriculumUrl: "https://www.tilburguniversity.edu/education/masters-programs/business-analytics-and-operations-research/program", eligibilityUrl: "https://www.tilburguniversity.edu/education/masters-programs/business-analytics-and-operations-research/application", materialsUrl: "https://www.tilburguniversity.edu/education/masters-programs/admission-application/course-lists", careersUrl: "https://www.tilburguniversity.edu/education/masters-programs/business-analytics-and-operations-research", premasterUrl: "https://www.tilburguniversity.edu/education/masters-programs/business-analytics-and-operations-research/premaster", tuitionUrl: "https://www.tilburguniversity.edu/education/masters-programs/tuition-fees-scholarships", studielinkUrl: STUDIELINK },
  }),
  define({
    id: "tilburg-management-analytics", institutionIds: ["tilburg"], name: "Research Master in Economics — Management Analytics", categories: ["business", "data"],
    sourceUrl: "https://www.tilburguniversity.edu/education/masters-programs/management-analytics", faculty: "Tilburg School of Economics and Management", duration: "2 years", ects: "120 ECTS", intakes: ["End of August"], deadline: "", tuition: "€23,900（非欧盟）", tuitionEur: 23900, tuitionAcademicYear: "2026/27",
    campusName: "Tilburg University Campus", city: "Tilburg", locationNotes: "Research Master in Economics 下的研究型 track；含 15 ECTS internship 与 27 ECTS thesis。",
    overview: { title: "Management Analytics", sourceUrl: "https://www.tilburguniversity.edu/education/masters-programs/management-analytics", sourceTitle: "Tilburg programme page", originalText: "Combine management and business economics with data science and AI.", summaryZh: "把管理、商业经济、数据科学与 AI 用于会计、金融、战略、营销、运筹和供应链问题。", fetchedAt: FETCHED_AT, origin: "official", locked: false },
    coreCourses: [course("Data Science Research Methods", "数据科学研究方法", "https://www.tilburguniversity.edu/education/masters-programs/management-analytics/program", ["data", "research methods"]), course("Quantitative Methods", "定量方法", "https://www.tilburguniversity.edu/education/masters-programs/management-analytics/program", ["mathematics", "statistics"]), course("Foundations of Econometrics", "计量经济学基础", "https://www.tilburguniversity.edu/education/masters-programs/management-analytics/program", ["econometrics"])],
    admissionCriteria: [criterion("tilburg-ma-gpa", "gpa", "优秀成绩", "Management Analytics 申请人通常需位于所在年级前 20%。", "https://www.tilburguniversity.edu/education/masters-programs/research-master-economics-academic-economics/application"), criterion("tilburg-ma-gre", "language", "GRE / GMAT 定量成绩", "非豁免申请人需达到 GRE Quantitative 162 或官网列示的 GMAT Quantitative 门槛。", "https://www.tilburguniversity.edu/education/masters-programs/research-master-economics-academic-economics/application", { testType: "GRE", minimum: 162, tags: ["GRE"] })], requirements: [], premaster: "不提供 pre-master",
    applicationLinks: { programUrl: "https://www.tilburguniversity.edu/education/masters-programs/management-analytics", curriculumUrl: "https://www.tilburguniversity.edu/education/masters-programs/management-analytics/program", eligibilityUrl: "https://www.tilburguniversity.edu/education/masters-programs/research-master-economics-academic-economics/application", materialsUrl: "https://www.tilburguniversity.edu/education/masters-programs/research-master-economics-academic-economics/application", careersUrl: "https://www.tilburguniversity.edu/education/masters-programs/management-analytics/career", premasterUrl: "", tuitionUrl: "https://www.tilburguniversity.edu/education/masters-programs/tuition-fees-scholarships", studielinkUrl: STUDIELINK },
  }),
];

export const catalogExpansionIds = new Set(catalogExpansionPrograms.map((program) => program.id));
